### ISSUE TITLE
Open source the integrations server

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/element-integration-manager#86]
The integration server provides some of the core ideals of matrix: integrating other services and allowing easy bridging to other networks that are available.

As such a proprietary component used to provide this feels very much out of place in the otherwise open source matrix ecosystem. I get that new vector is looking at ways to monetize some aspects of matrix, which is perfectly fine, and writing some proprietary services or bridges makes sense in that context, but having riot for everyone on mobile and most on web to use a closed source solution seems quite contrary to the matrix philosophy. 

This should also solve [this issue that keeps riot labeled with nonfreenet on f-droid](https://github.com/vector-im/riot-android/issues/2657).

[edit]If this is in the wrong repository, please feel free to move, or ask me to move it.

**Comment by richvdh** [comment]
Seems like this is no longer relevant? Can it be closed?

**Comment by Half-Shot** [comment]
Yes, believe so. https://github.com/vector-im/element-integration-manager/issues/86#issuecomment-1503820414 still stands, though with a few new updates:

- Scalar has been fully decommissioned and is no longer relevant.
- The new integration manager will not be open sourced *but* previously closed source components of Scalar have open source replacements. The Hookshot, IRC and Slack bridges are now providing their own interfaces as part of the applications, which is fully open source. The integration manager now only provides a wrapper around those.

**Comment by progval** [comment]
> The new integration manager will not be open sourced

Why?

**Comment by tengkuizdihar** [comment]
Bumping up this issue again, may we get a list of closed sourced component that's used in the matrix ecosystem by your company beside this integration manager @Half-Shot?

I'm using and supporting the use of matrix because of its open source nature, it would be weird if one of the nice things about it somehow implemented in closed sourced way.

**Comment by ara4n** [comment]
Element's integration manager happens to be proprietary, and always has been since it was created in 2017 or so.

Meanwhile, open source integration managers also exist, like https://dimension.t2bot.io/ - and folks are very welcome to write their own. (It's not even that hard, as Dimension shows).

> may we get a list of closed sourced component that's used in the matrix ecosystem by your company beside this integration manager

Element has a bunch of proprietary products, which we use to try to fund our salaries to keep working on Matrix. https://element.io/server-suite has a list of them.

Just because Element happens to sell some proprietary products does **NOT** mean that Matrix itself is in any way proprietary; it's just that being an open standard, people can choose whatever license they like to build on top.  For instance, Beeper is a proprietary Matrix client.  Element is a FOSS Matrix client.  The Integration Manager is a proprietary component.

Element has no plans to FOSS the integration manager right now - we are continuing to fight to get to break-even (i.e. stop losing money), and we need everything we can to do so.

**Comment by t3chguy** [comment]
> Meanwhile, open source integration managers also exist, like [dimension.t2bot.io](https://dimension.t2bot.io/)

Worth noting Dimension is no longer maintained and has been archived https://github.com/turt2live/matrix-dimension#-project-archived
